-- 1. Tạo tài khoản Admin
INSERT INTO public.users (username, email, password, role, balance) VALUES ('admin', 'admin@thanox.vn', 'Admin@123456', 'admin', 5000000);

-- 2. Thêm Sản phẩm
INSERT INTO public.products (name, category, price, seller_price, stock, status, description, image_url, hidden_keys_or_links) VALUES ('Thanox Pro Android - Gói Vĩnh Viễn Tối Ưu', 'FILE ANDROID', 30000, 30000, 'unlimited', 'active', 'File tối ưu hóa Android chuyên sâu, tăng 60-120 FPS, giảm giật lag và tối ưu pin cực đỉnh.', 'https://images.unsplash.com/photo-1550745165-9bc0b252726f?auto=format&fit=crop&w=600&q=80', 'https://drive.google.com/file/d/thanox-pro-android-v2.5/view?usp=sharing
Key Kích Hoạt: TX-PRO-AND-889922');
INSERT INTO public.products (name, category, price, seller_price, stock, status, description, image_url, hidden_keys_or_links) VALUES ('Module Magisk Thanox Kernel Extreme', 'FILE ANDROID', 49000, 49000, 'unlimited', 'active', 'Module tối ưu xung nhịp CPU/GPU qua Magisk & KernelSU, mở khóa 120 FPS mọi tựa game.', 'https://images.unsplash.com/photo-1542751371-adc38448a05e?auto=format&fit=crop&w=600&q=80', 'https://drive.google.com/file/d/magisk-thanox-kernel/view?usp=sharing');
INSERT INTO public.products (name, category, price, seller_price, stock, status, description, image_url, hidden_keys_or_links) VALUES ('Chứng Chỉ iOS Thanox VIP - Ký App Trọn Đời', 'FILE IOS', 199000, 199000, 'unlimited', 'active', 'Chứng chỉ Certificate P12 + MobileProvision cài IPA không thu hồi, bảo hành 1 năm 1 đổi 1.', 'https://images.unsplash.com/photo-1512499617640-c74ae3a79d37?auto=format&fit=crop&w=600&q=80', 'https://drive.google.com/file/d/ios-cert-p12-vip/view?usp=sharing
Pass: Thanox2026');
INSERT INTO public.products (name, category, price, seller_price, stock, status, description, image_url, hidden_keys_or_links) VALUES ('Menu Free Fire VIP - MIGUL PRO Antiban', 'MENU FF', 30000, 30000, 'unlimited', 'active', 'Menu hỗ trợ kéo tâm mượt mà, định vị địch chuẩn xác, bypass chống khóa nick rank cao.', 'https://images.unsplash.com/photo-1511512578047-dfb367046420?auto=format&fit=crop&w=600&q=80', 'Key: FF-MIGUL-30D-998877
Link Tải Menu: https://drive.google.com/file/d/menu-ff-v2/view');
INSERT INTO public.products (name, category, price, seller_price, stock, status, description, image_url, hidden_keys_or_links) VALUES ('Key Bản Quyền Thanox Tool 30 Ngày', 'KEY VIP', 50000, 50000, 'unlimited', 'active', 'Key kích hoạt full tính năng Thanox App trong 30 ngày, tự động kích hoạt ngay sau thanh toán.', 'https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?auto=format&fit=crop&w=600&q=80', 'THAN-OX-30D-AUTO-KEY-VALID');
INSERT INTO public.products (name, category, price, seller_price, stock, status, description, image_url, hidden_keys_or_links) VALUES ('Proxy IPv4 Riêng Biệt Tốc Độ Cao 1Gbps', 'PROXY RIÊNG', 35000, 35000, 'unlimited', 'active', 'Proxy sạch tĩnh Việt Nam (Viettel/FPT), ping 1ms, không giới hạn băng thông.', 'https://images.unsplash.com/photo-1544197150-b99a580bb7a8?auto=format&fit=crop&w=600&q=80', 'IP: 103.149.28.115:8080:thanox:proxyvip2026');
INSERT INTO public.products (name, category, price, seller_price, stock, status, description, image_url, hidden_keys_or_links) VALUES ('Acc Free Fire VIP - Full Skin Súng & Rank Cao Thủ', 'Tài Khoản Game', 150000, 120000, '5', 'active', 'Tài khoản Free Fire Rank Cao Thủ, full skin súng AK Rồng Xanh lv7, MP40 Mãng Xà. Đăng nhập sạch 100%, bảo hành đổi trả.', 'https://images.unsplash.com/photo-1542751371-adc38448a05e?auto=format&fit=crop&w=600&q=80', '🎮 TÀI KHOẢN: thanhgame.ff01@gmail.com
🔑 MẬT KHẨU: FreeFire@VIP2026
🛡️ MÃ 2FA / GHI CHÚ: 894012 (Đăng nhập qua VK / Facebook)');
