import React, { useState, useMemo, useEffect } from 'react';
import { useStore } from '../../context/StoreContext';
import { supabase } from '../../lib/supabase';
import { Button } from '../ui/Button';
import { Badge } from '../ui/Badge';
import { CardNetwork } from '../../types';
import {
  QrCode,
  Copy,
  Check,
  CheckCircle2,
  Clock,
  AlertCircle,
  Sparkles,
  Zap,
  Wallet,
  Building2,
  CreditCard,
  UserCheck,
  Send,
  PhoneCall,
  MessageSquare,
  Lock,
  ArrowRight,
  ShieldCheck,
  Smartphone,
  Info,
} from 'lucide-react';

const PRESET_AMOUNTS = [
  10000,
  50000,
  100000,
  200000,
  500000,
  1000000,
  2000000,
  5000000,
  10000000,
];

const CARD_DENOMINATIONS = [
  10000,
  20000,
  30000,
  50000,
  100000,
  200000,
  300000,
  500000,
  1000000,
];

export const StorefrontDepositQR: React.FC = () => {
  const {
    settings,
    currentUser,
    isAuthenticated,
    topups,
    cardRecharges,
    createTopupRequest,
    createCardRecharge,
    showToast,
    navigateToStorefront,
  } = useStore();

  // Channel switcher: VietQR Bank vs Card Recharge
  const [depositChannel, setDepositChannel] = useState<'vietqr' | 'card'>('vietqr');

  // Card Recharge State
  const [cardNetwork, setCardNetwork] = useState<CardNetwork>('Viettel');
  const [cardAmount, setCardAmount] = useState<number>(50000);
  const [cardSerial, setCardSerial] = useState<string>('');
  const [cardPin, setCardPin] = useState<string>('');
  const [isSubmittingCard, setIsSubmittingCard] = useState<boolean>(false);

  const minDeposit = settings.minDeposit || 10000;
  const maxDeposit = settings.maxDeposit || 10000000;

  // Selected or typed amount. Initial state is 0 (NO QR generated by default)
  const [selectedPreset, setSelectedPreset] = useState<number | null>(null);
  const [customAmountText, setCustomAmountText] = useState<string>('');
  const [activeAmount, setActiveAmount] = useState<number>(0);
  const [isTyping, setIsTyping] = useState<boolean>(false);

  const [copiedField, setCopiedField] = useState<string | null>(null);
  const [isSubmitting, setIsSubmitting] = useState<boolean>(false);
  const [lastSubmittedCode, setLastSubmittedCode] = useState<string | null>(null);
  const [qrLoadError, setQrLoadError] = useState<boolean>(false);

  // Dynamic Transaction Code for current valid amount session (STT<random_code>)
  const [transactionCode, setTransactionCode] = useState<string>('');
  const [timeLeft, setTimeLeft] = useState<number | null>(null);

  useEffect(() => {
    if (transactionCode) setTimeLeft(300);
    else setTimeLeft(null);
  }, [transactionCode]);

  useEffect(() => {
    if (timeLeft === null || timeLeft <= 0) return;
    const timerId = setTimeout(() => setTimeLeft((prev) => (prev ? prev - 1 : 0)), 1000);
    return () => clearTimeout(timerId);
  }, [timeLeft]);

  useEffect(() => {
    if (timeLeft === 0 && transactionCode) {
      showToast('Thời gian giao dịch đã hết hạn (5 phút). Vui lòng chọn lại số tiền!', 'error');
      setTransactionCode('');
      setActiveAmount(0);
      setSelectedPreset(null);
      setTimeLeft(null);
    }
  }, [timeLeft, transactionCode, showToast]);

  // Generate a fresh unique transaction code when a valid amount is selected (STT + alphanumeric)
  const generateNewTransactionCode = () => {
    const prefix = (settings.transferPrefix || 'STT').trim();
    const chars = '23456789ABCDEFGHJKLMNPQRSTUVWXYZ';
    let randomPart = '';
    for (let i = 0; i < 6; i++) {
      randomPart += chars.charAt(Math.floor(Math.random() * chars.length));
    }
    return `${prefix}${randomPart}`;
  };

  // Guests must log in first: deposit money only after signing in
  const DEPOSIT_REDIRECT = '/account/wallet/deposit';
  useEffect(() => {
    if (!isAuthenticated) {
      showToast('Vui lÃ²ng Ä‘Äƒng nháº­p tÃ i khoáº£n trÆ°á»›c khi náº¡p tiá»n!', 'warning');
      navigateToStorefront('login', DEPOSIT_REDIRECT);
    }
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [isAuthenticated]);

  // Auto-scroll the QR section into view when an amount becomes valid
  const scrollToQrSection = () => {
    setTimeout(() => {
      const qrEl = document.getElementById('deposit-qr-section');
      if (qrEl) qrEl.scrollIntoView({ behavior: 'smooth', block: 'start' });
    }, 120);
  };

  // Handle Preset Click
  const handleSelectPreset = (amt: number) => {
    if (!isAuthenticated) {
      showToast('Vui lÃ²ng Ä‘Äƒng nháº­p tÃ i khoáº£n trÆ°á»›c khi náº¡p tiá»n!', 'warning');
      navigateToStorefront('login', DEPOSIT_REDIRECT);
      return;
    }
    setIsTyping(false);
    setSelectedPreset(amt);
    setCustomAmountText(amt.toLocaleString('vi-VN'));
    setActiveAmount(amt);
    setQrLoadError(false);
    // Always generate a new unique code on amount selection
    setTransactionCode(generateNewTransactionCode());
    scrollToQrSection();
  };

  // Debounced Custom Amount Input
  useEffect(() => {
    if (!isTyping) return;

    const timer = setTimeout(() => {
      const numericValue = parseInt(customAmountText.replace(/\D/g, ''), 10);
        if (!customAmountText || isNaN(numericValue) || numericValue === 0) {
        setActiveAmount(0);
        setSelectedPreset(null);
        setTransactionCode('');
      } else {
        setActiveAmount(numericValue);
        setSelectedPreset(PRESET_AMOUNTS.includes(numericValue) ? numericValue : null);
        if (numericValue >= minDeposit && numericValue <= maxDeposit) {
          setTransactionCode(generateNewTransactionCode());
          scrollToQrSection();
        } else {
          setTransactionCode('');
        }
      }
    }, 250);

    return () => clearTimeout(timer);
  }, [customAmountText, isTyping, minDeposit, maxDeposit]);

const isAmountEntered = activeAmount > 0;
  const isBelowMin = isAmountEntered && activeAmount < minDeposit;
  const isAboveMax = isAmountEntered && activeAmount > maxDeposit;
  const isValidAmount = isAmountEntered && !isBelowMin && !isAboveMax;

  // Real-time Bank Reconciliation Polling (Checks every 3.5s)
  useEffect(() => {
    if (!transactionCode || !isValidAmount) return;

    let isSubscribed = true;
    const interval = setInterval(async () => {
      try {
        // Poll báº£ng topups trÃªn Supabase (RLS chá»‰ cho xem topup cá»§a chÃ­nh mÃ¬nh) â€”
        // thay cho endpoint legacy /api/deposit/status khÃ´ng tá»“n táº¡i trÃªn Vercel
        const { data } = await supabase
          .from('topups')
          .select('id, status, amount')
          .ilike('transfer_note', '%' + transactionCode + '%')
          .eq('status', 'approved')
          .limit(1);
        if (isSubscribed && data && data.length > 0) {
          showToast(`âš¡ Nháº­n tiá»n thÃ nh cÃ´ng! ÄÃ£ cá»™ng ${(data[0].amount || activeAmount).toLocaleString('vi-VN')}Ä‘ vÃ o vÃ­`, 'success');
          clearInterval(interval);
        }
      } catch {}
    }, 3500);

    return () => {
      isSubscribed = false;
      clearInterval(interval);
    };
  }, [transactionCode, isValidAmount, activeAmount, showToast]);

  const handleCustomAmountChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    setIsTyping(true);
    const raw = e.target.value.replace(/\D/g, '');
    if (!raw) {
      setCustomAmountText('');
      setActiveAmount(0);
      setSelectedPreset(null);
      setTransactionCode('');
      return;
    }
    const num = parseInt(raw, 10);
    if (isNaN(num)) {
      setCustomAmountText('');
      setActiveAmount(0);
      setSelectedPreset(null);
      setTransactionCode('');
    } else {
      setCustomAmountText(num.toLocaleString('vi-VN'));
    }
  };

  // Validation logic
  
  // Safe extraction helpers to prevent object as child errors
  const safeAccountNumber = typeof settings.bankAccount === 'string' ? settings.bankAccount : (settings.bankAccount as any)?.accountNumber || '0326884292';
  const safeBankName = typeof settings.bankName === 'string' ? settings.bankName : (settings.bankAccount as any)?.bankName || 'MBBank QuÃ¢n Äá»™i';
  const safeBankCode = typeof settings.bankCode === 'string' ? settings.bankCode : 'MB';
  const safeAccountHolder = typeof settings.accountHolder === 'string' ? settings.accountHolder : (settings.bankAccount as any)?.accountHolder || 'TRAN QUANG THANH';

  // Multi-tier resilient VietQR URLs with automatic fallback
  const [qrFallbackIndex, setQrFallbackIndex] = useState(0);

  const qrUrls = useMemo(() => {
    if (!isValidAmount || !transactionCode) return [];
    const bankCode = safeBankCode || 'MB';
    const bankAccount = safeAccountNumber || '0326884292';
    const accountHolder = safeAccountHolder || 'TRAN QUANG THANH';
    const memo = transactionCode;
    const template = settings.qrTemplate || 'compact2';

    return [
      `https://img.vietqr.io/image/${bankCode}-${bankAccount}-${template}.png?amount=${activeAmount}&addInfo=${encodeURIComponent(memo)}&accountName=${encodeURIComponent(accountHolder)}`,
      `https://api.vietqr.io/image/${bankCode}-${bankAccount}-${template}.jpg?amount=${activeAmount}&addInfo=${encodeURIComponent(memo)}&accountName=${encodeURIComponent(accountHolder)}`,
      `https://api.qrserver.com/v1/create-qr-code/?size=300x300&data=${encodeURIComponent(`https://img.vietqr.io/image/${bankCode}-${bankAccount}-${template}.png?amount=${activeAmount}&addInfo=${encodeURIComponent(memo)}&accountName=${encodeURIComponent(accountHolder)}`)}&margin=10`,
      `https://quickchart.io/qr?text=${encodeURIComponent(`https://img.vietqr.io/image/${bankCode}-${bankAccount}-${template}.png?amount=${activeAmount}&addInfo=${encodeURIComponent(memo)}&accountName=${encodeURIComponent(accountHolder)}`)}&size=300`,
    ];
  }, [isValidAmount, activeAmount, transactionCode, safeBankCode, safeAccountNumber, safeAccountHolder, settings.qrTemplate]);

  const activeQrUrl = qrUrls[qrFallbackIndex] || qrUrls[0];

  const copyToClipboard = (text: string, fieldName: string) => {
    navigator.clipboard.writeText(text);
    setCopiedField(fieldName);
    showToast(`ÄÃ£ sao chÃ©p ${fieldName}`, 'success');
    setTimeout(() => setCopiedField(null), 2000);
  };

  const handleSubmitDeposit = () => {
    if (!isAuthenticated) {
      showToast('Vui lÃ²ng Ä‘Äƒng nháº­p tÃ i khoáº£n trÆ°á»›c khi táº¡o yÃªu cáº§u náº¡p tiá»n.', 'warning');
      navigateToStorefront('login', DEPOSIT_REDIRECT);
      return;
    }
    if (!isValidAmount) {
      if (activeAmount < minDeposit) {
        showToast(`Sá»‘ tiá»n náº¡p tá»‘i thiá»ƒu lÃ  ${minDeposit.toLocaleString('vi-VN')}Ä‘`, 'error');
      } else if (activeAmount > maxDeposit) {
        showToast(`Sá»‘ tiá»n náº¡p tá»‘i Ä‘a lÃ  ${maxDeposit.toLocaleString('vi-VN')}Ä‘`, 'error');
      } else {
        showToast('Vui lÃ²ng chá»n hoáº·c nháº­p sá»‘ tiá»n náº¡p há»£p lá»‡', 'error');
      }
      return;
    }
    if (!transactionCode) {
      showToast('MÃ£ giao dá»‹ch khÃ´ng há»£p lá»‡, vui lÃ²ng chá»n láº¡i sá»‘ tiá»n', 'error');
      return;
    }
    setIsSubmitting(true);
    setTimeout(() => {
      const code = createTopupRequest(activeAmount, 'Bank Transfer', transactionCode);
      setIsSubmitting(false);
      showToast(`ÄÃ£ táº¡o yÃªu cáº§u náº¡p tiá»n ${activeAmount.toLocaleString('vi-VN')}Ä‘ thÃ nh cÃ´ng!`, 'success');
    }, 400);
  };

  const handleCardRechargeSubmit = (e: React.FormEvent) => {
    e.preventDefault();
    if (!isAuthenticated) {
      showToast('Vui lÃ²ng Ä‘Äƒng nháº­p tÃ i khoáº£n trÆ°á»›c khi náº¡p tháº» cÃ o.', 'warning');
      navigateToStorefront('login', DEPOSIT_REDIRECT);
      return;
    }
    if (!cardSerial.trim() || cardSerial.trim().length < 6) {
      showToast('Vui lÃ²ng nháº­p sá»‘ Serial tháº» há»£p lá»‡ (tá»‘i thiá»ƒu 6 kÃ½ tá»±)', 'error');
      return;
    }
    if (!cardPin.trim() || cardPin.trim().length < 6) {
      showToast('Vui lÃ²ng nháº­p MÃ£ Tháº» (PIN) há»£p lá»‡ (tá»‘i thiá»ƒu 6 kÃ½ tá»±)', 'error');
      return;
    }
    setIsSubmittingCard(true);
    setTimeout(() => {
      createCardRecharge(cardNetwork, cardAmount, cardSerial.trim(), cardPin.trim());
      setCardSerial('');
      setCardPin('');
      setIsSubmittingCard(false);
    }, 500);
  };

  const userTopups = useMemo(() => {
    return topups.filter((t) => t.userId === currentUser.id);
  }, [topups, currentUser.id]);

  const userCards = useMemo(() => {
    return cardRecharges.filter((c) => c.userId === currentUser.id);
  }, [cardRecharges, currentUser.id]);

  const currentNetworkKey = (cardNetwork || 'VIETTEL').toUpperCase();
  const networkConfigs = settings.cardSettings?.networkMatrix?.[currentNetworkKey] || [];
  const matchedConfig = networkConfigs.find((c) => c.amount === cardAmount);

  const cardFeePercent = matchedConfig ? matchedConfig.feePercent : (settings.cardSettings?.feePercentage ?? 15);
  const cardReceiveAmount = matchedConfig ? matchedConfig.receiveAmount : Math.round(cardAmount * (1 - cardFeePercent / 100));

  return (
    <div className="max-w-5xl mx-auto space-y-8 py-4">
      {!isAuthenticated && (
        <div className="p-4 rounded-2xl bg-amber-500/10 border border-amber-500/30 flex flex-col sm:flex-row sm:items-center justify-between gap-4">
          <div className="flex items-center gap-3">
            <Lock className="w-5 h-5 text-amber-400 flex-shrink-0" />
            <div>
              <div className="font-bold text-xs text-amber-200">Báº¡n chÆ°a Ä‘Äƒng nháº­p tÃ i khoáº£n</div>
              <div className="text-[11px] text-amber-300/80">
                HÃ£y Ä‘Äƒng nháº­p Ä‘á»ƒ há»‡ thá»‘ng tá»± Ä‘á»™ng cá»™ng tiá»n vÃ o vÃ­ tÃ i khoáº£n cá»§a báº¡n sau khi chuyá»ƒn khoáº£n hoáº·c gá»­i tháº» cÃ o.
              </div>
            </div>
          </div>
          <button
            onClick={() => navigateToStorefront('login', DEPOSIT_REDIRECT)}
            className="px-4 py-2 rounded-xl bg-amber-500 hover:bg-amber-600 text-black text-xs font-bold transition-colors cursor-pointer self-start sm:self-auto flex items-center gap-1.5 whitespace-nowrap"
          >
            ÄÄƒng Nháº­p Ngay <ArrowRight className="w-3.5 h-3.5" />
          </button>
        </div>
      )}

      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4 border-b border-white/5 pb-6">
        <div>
          <div className="flex items-center gap-2 text-xs text-[#8B84A8] mb-1.5">
            <button onClick={() => navigateToStorefront('home')} className="hover:text-white transition-colors cursor-pointer">Trang Chá»§</button>
            <span>/</span>
            <button onClick={() => navigateToStorefront('account')} className="hover:text-white transition-colors cursor-pointer">TÃ i Khoáº£n</button>
            <span>/</span>
            <span className="text-[#9D5CF6] font-medium">Náº¡p tiá»n</span>
          </div>
          <h1 className="font-display text-2xl sm:text-3xl font-extrabold text-[#F0EDFF] tracking-tight">
            Náº¡p tiá»n vÃ o tÃ i khoáº£n
          </h1>
          <p className="text-xs sm:text-sm text-[#8B84A8] mt-1 font-medium">
            Há»— trá»£ chuyá»ƒn khoáº£n ngÃ¢n hÃ ng VietQR tá»± Ä‘á»™ng 24/7 vÃ  gáº¡ch tháº» cÃ o Ä‘iá»‡n thoáº¡i / game
          </p>
        </div>

        <div className="flex items-center gap-3 bg-[rgba(255,255,255,0.05)] backdrop-blur-[26px] border border-white/10 p-3.5 rounded-2xl shadow-[0_10px_30px_rgba(0,0,0,0.25)]">
          <div className="w-10 h-10 rounded-xl bg-[#7C3AED]/20 border border-[#7C3AED]/30 flex items-center justify-center text-[#9D5CF6]">
            <Wallet className="w-5 h-5" />
          </div>
          <div>
            <div className="text-[11px] font-semibold text-[#8B84A8] uppercase tracking-wider">Sá»‘ dÆ° vÃ­ cá»§a báº¡n</div>
            <div className="font-display text-lg font-bold text-emerald-400">
              {currentUser.balance.toLocaleString('vi-VN')} <span className="text-xs font-normal">Ä‘</span>
            </div>
          </div>
        </div>
      </div>

      <div className="flex items-center gap-3 border-b border-white/10 pb-4">
        <button
          type="button"
          onClick={() => setDepositChannel('vietqr')}
          className={`flex items-center gap-2.5 px-5 py-3 rounded-2xl font-bold text-xs transition-all cursor-pointer border ${
            depositChannel === 'vietqr'
              ? 'bg-[#7C3AED] text-white border-[#9D5CF6] shadow-lg shadow-[#7C3AED]/30'
              : 'bg-[#161626]/80 text-[#8B84A8] border-white/5 hover:text-white hover:border-white/15'
          }`}
        >
          <QrCode className="w-4 h-4" />
          <span>Chuyá»ƒn Khoáº£n NgÃ¢n HÃ ng (VietQR)</span>
          <span className="px-1.5 py-0.5 rounded-md text-[10px] bg-emerald-400/20 text-emerald-300 font-bold ml-1">
            KhuyÃªn DÃ¹ng
          </span>
        </button>

        <button
          type="button"
          onClick={() => setDepositChannel('card')}
          className={`flex items-center gap-2.5 px-5 py-3 rounded-2xl font-bold text-xs transition-all cursor-pointer border ${
            depositChannel === 'card'
              ? 'bg-[#7C3AED] text-white border-[#9D5CF6] shadow-lg shadow-[#7C3AED]/30'
              : 'bg-[#161626]/80 text-[#8B84A8] border-white/5 hover:text-white hover:border-white/15'
          }`}
        >
          <Smartphone className="w-4 h-4" />
          <span>Náº¡p Tháº» CÃ o Äiá»‡n Thoáº¡i / Game</span>
          <span className="px-1.5 py-0.5 rounded-md text-[10px] bg-amber-400/20 text-amber-300 font-bold ml-1">
            Chiáº¿t kháº¥u {cardFeePercent}%
          </span>
        </button>
      </div>

      {depositChannel === 'vietqr' && (
        <>
          <div className="grid grid-cols-1 lg:grid-cols-12 gap-6">
            <div className="lg:col-span-5 space-y-6">
              <div className="bg-[rgba(255,255,255,0.05)] backdrop-blur-[26px] border border-white/10 shadow-[0_20px_60px_rgba(0,0,0,0.35)] rounded-3xl p-6 space-y-3">
                <div className="flex items-center gap-2 text-xs font-bold text-[#F0EDFF] uppercase tracking-wider">
                  <Building2 className="w-4 h-4 text-[#9D5CF6]" />
                  <span>KÃªnh Chuyá»ƒn Khoáº£n MBBank</span>
                </div>
                <div className="p-3.5 rounded-2xl bg-[#161626]/80 border border-white/5 space-y-1">
                  <div className="text-xs font-semibold text-[#F0EDFF]">
                    {safeBankName} ({safeBankCode})
                  </div>
                  <div className="text-[11px] text-[#8B84A8]">
                    STK: <strong className="font-mono text-cyan-400">{safeAccountNumber}</strong>
                  </div>
                  <div className="text-[11px] text-[#8B84A8]">
                    Chá»§ TK: <strong className="text-white">{safeAccountHolder}</strong>
                  </div>
                </div>
              </div>

              <div className="bg-[rgba(255,255,255,0.05)] backdrop-blur-[26px] border border-white/10 shadow-[0_20px_60px_rgba(0,0,0,0.35)] rounded-3xl p-6 space-y-4">
                <div className="flex items-center justify-between">
                  <div className="flex items-center gap-2 text-xs font-bold text-[#F0EDFF] uppercase tracking-wider">
                    <Sparkles className="w-4 h-4 text-amber-400" />
                    <span>Chá»n sá»‘ tiá»n náº¡p</span>
                  </div>
                  <span className="text-[11px] font-semibold text-[#9D5CF6]">
                    {minDeposit.toLocaleString('vi-VN')}Ä‘ â€“ {maxDeposit.toLocaleString('vi-VN')}Ä‘
                  </span>
                </div>

                <div className="space-y-1.5">
                  <label className="text-[11px] font-semibold text-[#8B84A8]">Nháº­p sá»‘ tiá»n:</label>
                  <div className="relative">
                    <input
                      type="text"
                      placeholder="Nháº­p sá»‘ tiá»n (VD: 50,000 / 200,000)..."
                      value={customAmountText}
                      onChange={handleCustomAmountChange}
                      className={`w-full bg-[#161626]/90 border rounded-2xl pl-4 pr-10 py-3 text-sm text-[#F0EDFF] font-bold focus:outline-none transition-colors ${
                        isBelowMin || isAboveMax
                          ? 'border-red-500/60 focus:border-red-500'
                          : isValidAmount
                          ? 'border-emerald-500/60 focus:border-emerald-500'
                          : 'border-white/10 focus:border-[#7C3AED]'
                      }`}
                    />
                    <span className="absolute right-3.5 top-1/2 -translate-y-1/2 text-xs font-bold text-[#8B84A8]">
                      VNÄ
                    </span>
                  </div>

                  {isBelowMin && (
                    <p className="text-[11px] text-red-400 flex items-center gap-1 font-medium pt-0.5">
                      <AlertCircle className="w-3.5 h-3.5" />
                      Sá»‘ tiá»n náº¡p tá»‘i thiá»ƒu lÃ  {minDeposit.toLocaleString('vi-VN')}Ä‘
                    </p>
                  )}
                  {isAboveMax && (
                    <p className="text-[11px] text-red-400 flex items-center gap-1 font-medium pt-0.5">
                      <AlertCircle className="w-3.5 h-3.5" />
                      Sá»‘ tiá»n náº¡p tá»‘i Ä‘a lÃ  {maxDeposit.toLocaleString('vi-VN')}Ä‘
                    </p>
                  )}
                </div>

                <div className="space-y-1.5 pt-1">
                  <div className="text-[11px] font-semibold text-[#8B84A8]">Má»©c náº¡p phá»• biáº¿n:</div>
                  <div className="grid grid-cols-3 gap-2">
                    {PRESET_AMOUNTS.map((amt) => {
                      const active = selectedPreset === amt;
                      const label =
                        amt >= 1000000
                          ? `${amt / 1000000}M`
                          : amt >= 1000
                          ? `${amt / 1000}K`
                          : `${amt}`;
                      return (
                        <button
                          key={amt}
                          type="button"
                          onClick={() => handleSelectPreset(amt)}
                          className={`py-2.5 px-2 rounded-2xl text-center font-bold text-xs transition-all cursor-pointer border ${
                            active
                              ? 'bg-[#7C3AED] text-white border-[#9D5CF6] shadow-md shadow-[#7C3AED]/30 scale-[1.02]'
                              : 'bg-[#161626]/80 text-[#CBC7E0] border-white/5 hover:border-white/20 hover:text-white'
                          }`}
                        >
                          {label}
                          <span className="text-[10px] font-normal text-white/70 block">
                            {amt.toLocaleString('vi-VN')}Ä‘
                          </span>
                        </button>
                      );
                    })}
                  </div>
                </div>

                {isValidAmount && (
                  <div className="p-3.5 rounded-2xl bg-[#7C3AED]/15 border border-[#7C3AED]/30 flex items-center justify-between text-xs">
                    <span className="text-[#CBC7E0] font-medium">Sá»‘ tiá»n thanh toÃ¡n:</span>
                    <span className="font-display font-extrabold text-lg text-emerald-400">
                      {activeAmount.toLocaleString('vi-VN')} <span className="text-xs font-bold text-emerald-300">Ä‘</span>
                    </span>
                  </div>
                )}
              </div>

              <div className="p-5 rounded-3xl bg-[rgba(255,255,255,0.05)] backdrop-blur-[26px] border border-white/10 text-xs space-y-2.5">
                <div className="flex items-center gap-2 font-bold text-[#F0EDFF]">
                  <MessageSquare className="w-4 h-4 text-[#9D5CF6]" />
                  <span>Há»— trá»£ náº¡p tiá»n 24/7</span>
                </div>
                <p className="text-[11.5px] leading-relaxed text-[#8B84A8]">
                  Náº¿u giao dá»‹ch chÆ°a cá»™ng tiá»n sau 3-5 phÃºt, vui lÃ²ng liÃªn há»‡ Admin Ä‘á»ƒ Ä‘Æ°á»£c há»— trá»£ kiá»ƒm tra tá»©c thÃ¬:
                </p>
                <div className="grid grid-cols-2 gap-2 pt-1">
                  <a
                    href="https://t.me/quangthank"
                    target="_blank"
                    rel="noreferrer"
                    className="p-2.5 rounded-xl bg-[#161626]/80 border border-white/5 hover:border-[#06B6D4]/40 flex items-center gap-1.5 text-[11px] text-[#06B6D4] font-semibold transition-colors"
                  >
                    <Send className="w-3.5 h-3.5" />
                    <span className="truncate">Telegram: @quangthank</span>
                  </a>
                  <a
                    href="https://zalo.me/0916396901"
                    target="_blank"
                    rel="noreferrer"
                    className="p-2.5 rounded-xl bg-[#161626]/80 border border-white/5 hover:border-emerald-400/40 flex items-center gap-1.5 text-[11px] text-emerald-400 font-semibold transition-colors"
                  >
                    <PhoneCall className="w-3.5 h-3.5" />
                    <span className="truncate">Zalo: 0916396901</span>
                  </a>
                </div>
              </div>
            </div>

            <div className="lg:col-span-7 space-y-6">
              <div id="deposit-qr-section" className="bg-[rgba(255,255,255,0.05)] backdrop-blur-[26px] border border-white/10 shadow-[0_20px_60px_rgba(0,0,0,0.35)] rounded-3xl p-6 sm:p-8 space-y-6">
                <div className="flex items-center justify-between border-b border-white/5 pb-4">
                  <div>
                    <h3 className="font-display font-bold text-base sm:text-lg text-[#F0EDFF] flex items-center gap-2">
                      <QrCode className="w-5 h-5 text-[#9D5CF6]" />
                      MÃ£ QR thanh toÃ¡n
                    </h3>
                    <p className="text-xs text-[#8B84A8] mt-0.5">
                      {isValidAmount
                        ? 'QuÃ©t mÃ£ Ä‘á»ƒ tá»± Ä‘á»™ng Ä‘iá»n sá»‘ tiá»n vÃ  ná»™i dung chuyá»ƒn khoáº£n chÃ­nh xÃ¡c'
                        : 'Vui lÃ²ng chá»n hoáº·c nháº­p sá»‘ tiá»n Ä‘á»ƒ táº¡o mÃ£ QR thanh toÃ¡n'}
                    </p>
                  </div>
                  <Badge variant="brand" size="sm" dot>
                    VietQR 24/7
                  </Badge>
                </div>

                {!isValidAmount ? (
                  <div className="py-14 px-6 rounded-2xl border border-dashed border-white/10 bg-[#161626]/40 text-center space-y-3">
                    <div className="w-16 h-16 rounded-2xl bg-white/5 border border-white/10 mx-auto flex items-center justify-center text-[#8B84A8]">
                      <QrCode className="w-8 h-8 opacity-60" />
                    </div>
                    <div>
                      <h4 className="font-display font-bold text-sm text-[#F0EDFF] uppercase tracking-wider">
                        ChÆ°a cÃ³ mÃ£ QR
                      </h4>
                      <p className="text-xs text-[#8B84A8] mt-1 max-w-sm mx-auto">
                        Vui lÃ²ng chá»n hoáº·c nháº­p sá»‘ tiá»n tá»«{' '}
                        <strong className="text-white">{minDeposit.toLocaleString('vi-VN')}Ä‘</strong> Ä‘áº¿n{' '}
                        <strong className="text-white">{maxDeposit.toLocaleString('vi-VN')}Ä‘</strong> Ä‘á»ƒ táº¡o mÃ£ QR thanh toÃ¡n.
                      </p>
                    </div>
                  </div>
                ) : (
                  <div className="grid grid-cols-1 sm:grid-cols-12 gap-6 items-center">
                    <div className="sm:col-span-6 flex flex-col items-center justify-center p-3 sm:p-5 bg-[#0F0F1A] rounded-2xl border border-white/5">
                      <div className="p-3 sm:p-4 bg-white rounded-2xl shadow-2xl shadow-cyan-500/10 border-2 border-cyan-400/40 w-full max-w-[280px] sm:max-w-[300px] flex items-center justify-center relative overflow-hidden group">
                        {/* 4 Cyber Corner Framing Brackets */}
                        <div className="vietqr-corner-bracket top-2 left-2 border-t-2 border-l-2 rounded-tl-sm" />
                        <div className="vietqr-corner-bracket top-2 right-2 border-t-2 border-r-2 rounded-tr-sm" />
                        <div className="vietqr-corner-bracket bottom-2 left-2 border-b-2 border-l-2 rounded-bl-sm" />
                        <div className="vietqr-corner-bracket bottom-2 right-2 border-b-2 border-r-2 rounded-br-sm" />

                        {/* Laser Scanner Line (QuÃ©t lÃªn quÃ©t xuá»‘ng) */}
                        {!qrLoadError && <div className="vietqr-scan-laser-line" />}

                        {qrLoadError ? (
                          <div className="aspect-square w-full flex flex-col items-center justify-center p-4 text-center text-zinc-800">
                            <AlertCircle className="w-8 h-8 text-red-500 mb-2" />
                            <p className="text-xs font-bold">KhÃ´ng thá»ƒ táº£i mÃ£ QR</p>
                            <button
                              type="button"
                              onClick={() => {
                                setQrFallbackIndex(0);
                                setQrLoadError(false);
                              }}
                              className="mt-3 px-3 py-1 bg-zinc-900 text-white text-[10px] font-bold rounded-lg cursor-pointer"
                            >
                              Thá»­ láº¡i
                            </button>
                          </div>
                        ) : (
                          <img
                            src={activeQrUrl}
                            alt={`VietQR ${activeAmount} VND`}
                            onError={() => {
                              if (qrFallbackIndex < qrUrls.length - 1) {
                                setQrFallbackIndex((prev) => prev + 1);
                              } else {
                                setQrLoadError(true);
                              }
                            }}
                            className="w-full aspect-square object-contain rounded-lg relative z-10"
                            referrerPolicy="no-referrer"
                          />
                        )}
                      </div>
                      <div className="mt-3 text-[11px] text-[#CBC7E0] text-center flex items-center justify-center gap-1.5 font-medium">
                        <Zap className="w-3.5 h-3.5 text-amber-400" />
                        Mở App Ngân Hàng - Quét mã (Hết hạn sau: {timeLeft ? `${Math.floor(timeLeft / 60)}:${String(timeLeft % 60).padStart(2, '0')}` : '05:00'})
                      </div>
                    </div>

                    <div className="sm:col-span-6 space-y-2.5 text-xs">
                      <div className="p-3 rounded-2xl bg-[#161626]/80 border border-white/5 flex items-center justify-between">
                        <div>
                          <div className="text-[10px] uppercase font-bold text-[#8B84A8]">NgÃ¢n hÃ ng nháº­n</div>
                          <div className="font-bold text-[#F0EDFF] text-xs mt-0.5">
                            {safeBankName} ({safeBankCode})
                          </div>
                        </div>
                        <Building2 className="w-4 h-4 text-[#8B84A8]" />
                      </div>

                      <div className="p-3 rounded-2xl bg-[#161626]/80 border border-white/5 flex items-center justify-between">
                        <div>
                          <div className="text-[10px] uppercase font-bold text-[#8B84A8]">Sá»‘ tÃ i khoáº£n</div>
                          <div className="font-mono font-bold text-sm text-[#06B6D4] mt-0.5">
                            {safeAccountNumber}
                          </div>
                        </div>
                        <button
                          type="button"
                          onClick={() => copyToClipboard(safeAccountNumber, 'Sá»‘ tÃ i khoáº£n')}
                          className="p-2 rounded-xl bg-white/5 hover:bg-white/10 text-[#CBC7E0] transition-colors cursor-pointer"
                        >
                          {copiedField === 'Sá»‘ tÃ i khoáº£n' ? (
                            <Check className="w-3.5 h-3.5 text-emerald-400" />
                          ) : (
                            <Copy className="w-3.5 h-3.5" />
                          )}
                        </button>
                      </div>

                      <div className="p-3 rounded-2xl bg-[#161626]/80 border border-white/5 flex items-center justify-between">
                        <div>
                          <div className="text-[10px] uppercase font-bold text-[#8B84A8]">Chá»§ tÃ i khoáº£n</div>
                          <div className="font-bold text-[#F0EDFF] uppercase text-xs mt-0.5">
                            {safeAccountHolder}
                          </div>
                        </div>
                        <UserCheck className="w-4 h-4 text-[#8B84A8]" />
                      </div>

                      <div className="p-3 rounded-2xl bg-[#161626]/80 border border-white/5 flex items-center justify-between">
                        <div>
                          <div className="text-[10px] uppercase font-bold text-[#8B84A8]">Sá»‘ tiá»n</div>
                          <div className="font-display font-bold text-sm text-emerald-400 mt-0.5">
                            {activeAmount.toLocaleString('vi-VN')} VND
                          </div>
                        </div>
                        <button
                          type="button"
                          onClick={() => copyToClipboard(activeAmount.toString(), 'Sá»‘ tiá»n')}
                          className="p-2 rounded-xl bg-white/5 hover:bg-white/10 text-[#CBC7E0] transition-colors cursor-pointer"
                        >
                          {copiedField === 'Sá»‘ tiá»n' ? (
                            <Check className="w-3.5 h-3.5 text-emerald-400" />
                          ) : (
                            <Copy className="w-3.5 h-3.5" />
                          )}
                        </button>
                      </div>

                      <div className="p-3 rounded-2xl bg-[#7C3AED]/15 border border-[#7C3AED]/40 flex items-center justify-between">
                        <div>
                          <div className="text-[10px] uppercase font-bold text-[#9D5CF6]">
                            Ná»™i dung chuyá»ƒn khoáº£n (Báº¯t buá»™c)
                          </div>
                          <div className="font-mono font-bold text-xs text-amber-300 tracking-wider mt-0.5">
                            {transactionCode}
                          </div>
                        </div>
                        <button
                          type="button"
                          onClick={() => copyToClipboard(transactionCode, 'Ná»™i dung')}
                          className="p-2 rounded-xl bg-[#7C3AED]/30 hover:bg-[#7C3AED]/50 text-[#F0EDFF] transition-colors cursor-pointer"
                        >
                          {copiedField === 'Ná»™i dung' ? (
                            <Check className="w-3.5 h-3.5 text-emerald-400" />
                          ) : (
                            <Copy className="w-3.5 h-3.5" />
                          )}
                        </button>
                      </div>
                    </div>
                  </div>
                )}

                <div className="pt-4 border-t border-white/5 space-y-3">
                  <Button
                    variant="primary"
                    size="lg"
                    className="w-full justify-center text-sm font-bold shadow-lg shadow-[#7C3AED]/20 cursor-pointer disabled:opacity-50 disabled:cursor-not-allowed"
                    disabled={!isValidAmount || isSubmitting || !transactionCode}
                    isLoading={isSubmitting}
                    onClick={handleSubmitDeposit}
                    leftIcon={<CheckCircle2 className="w-4 h-4" />}
                  >
                    TÃ´i ÄÃ£ Chuyá»ƒn Khoáº£n â€” XÃ¡c Nháº­n Náº¡p Tiá»n
                  </Button>

                  <div className="flex items-center justify-center gap-1.5 text-[11px] text-emerald-400 font-medium">
                    <Zap className="w-3.5 h-3.5 text-amber-300" />
                    <span>
                      âš¡ Há»‡ thá»‘ng tá»± Ä‘á»™ng Ä‘á»‘i soÃ¡t & cá»™ng tiá»n siÃªu tá»‘c trong 5-10 giÃ¢y. Tiá»n vÃ o vÃ­ tá»©c thÃ¬.
                    </span>
                  </div>
                </div>
              </div>
            </div>
          </div>

          <div className="bg-[rgba(255,255,255,0.05)] backdrop-blur-[26px] border border-white/10 shadow-[0_20px_60px_rgba(0,0,0,0.35)] rounded-3xl p-6 sm:p-8 space-y-4">
            <div className="flex items-center justify-between">
              <div className="flex items-center gap-2">
                <Clock className="w-4 h-4 text-[#9D5CF6]" />
                <h3 className="font-display font-bold text-sm sm:text-base text-[#F0EDFF]">
                  Lá»‹ch sá»­ náº¡p tiá»n VietQR
                </h3>
              </div>
              <span className="text-xs text-[#8B84A8]">{userTopups.length} giao dá»‹ch</span>
            </div>

            {userTopups.length === 0 ? (
              <div className="p-8 text-center text-xs text-[#8B84A8] border border-dashed border-white/5 rounded-2xl bg-[#161626]/30">
                Báº¡n chÆ°a cÃ³ yÃªu cáº§u náº¡p tiá»n nÃ o. HÃ£y chá»n má»©c náº¡p bÃªn trÃªn Ä‘á»ƒ báº¯t Ä‘áº§u!
              </div>
            ) : (
              <div className="overflow-x-auto">
                <table className="w-full text-left text-xs">
                  <thead>
                    <tr className="border-b border-white/5 text-[#8B84A8] text-[11px] uppercase">
                      <th className="pb-3 font-semibold">MÃ£ YÃªu Cáº§u</th>
                      <th className="pb-3 font-semibold">Sá»‘ Tiá»n</th>
                      <th className="pb-3 font-semibold">PhÆ°Æ¡ng Thá»©c</th>
                      <th className="pb-3 font-semibold">Ná»™i Dung</th>
                      <th className="pb-3 font-semibold">Thá»i Gian</th>
                      <th className="pb-3 font-semibold text-right">Tráº¡ng ThÃ¡i</th>
                    </tr>
                  </thead>
                  <tbody className="divide-y divide-white/5">
                    {userTopups.map((topup) => (
                      <tr key={topup.id} className="hover:bg-white/[0.02] transition-colors">
                        <td className="py-3 font-mono font-bold text-[#9D5CF6]">{topup.requestCode}</td>
                        <td className="py-3 font-display font-bold text-emerald-400">
                          +{topup.amount.toLocaleString('vi-VN')}Ä‘
                        </td>
                        <td className="py-3 text-[#CBC7E0]">{topup.method}</td>
                        <td className="py-3 font-mono text-[11px] text-[#8B84A8]">{topup.transferNote}</td>
                        <td className="py-3 text-[#8B84A8]">{topup.createdAt}</td>
                        <td className="py-3 text-right">
                          {topup.status === 'pending' && <Badge variant="warning" size="xs" dot>Chá» Duyá»‡t</Badge>}
                          {topup.status === 'processing' && <Badge variant="warning" size="xs" dot>Äang Xá»­ LÃ½</Badge>}
                          {topup.status === 'approved' && <Badge variant="success" size="xs">ÄÃ£ Cá»™ng Tiá»n</Badge>}
                          {topup.status === 'rejected' && <Badge variant="danger" size="xs">Tá»« Chá»‘i</Badge>}
                          {topup.status === 'cancelled' && <Badge variant="neutral" size="xs">ÄÃ£ Há»§y</Badge>}
                        </td>
                      </tr>
                    ))}
                  </tbody>
                </table>
              </div>
            )}
          </div>
        </>
      )}

      {depositChannel === 'card' && (
        <div className="space-y-6">
          <form onSubmit={handleCardRechargeSubmit} className="grid grid-cols-1 lg:grid-cols-12 gap-6">
            <div className="lg:col-span-7 bg-[rgba(255,255,255,0.05)] backdrop-blur-[26px] border border-white/10 shadow-[0_20px_60px_rgba(0,0,0,0.35)] rounded-3xl p-6 sm:p-8 space-y-5">
              <div className="flex items-center gap-2 border-b border-white/5 pb-3 font-bold text-sm text-[#F0EDFF]">
                <CreditCard className="w-4 h-4 text-[#06B6D4]" />
                <span>Nháº­p ThÃ´ng Tin Tháº» CÃ o</span>
              </div>

              <div className="space-y-2">
                <label className="text-[11px] font-semibold text-[#8B84A8] uppercase tracking-wider">
                  1. Chá»n Loáº¡i Tháº» / NhÃ  Máº¡ng
                </label>
                <div className="grid grid-cols-3 sm:grid-cols-6 gap-2">
                  {(['Viettel', 'Vinaphone', 'Mobifone', 'Vietnamobile', 'Zing', 'Garena'] as CardNetwork[]).map((net) => {
                    const active = cardNetwork === net;
                    return (
                      <button
                        key={net}
                        type="button"
                        onClick={() => setCardNetwork(net)}
                        className={`py-2.5 px-2 rounded-2xl text-center font-bold text-xs transition-all cursor-pointer border ${
                          active
                            ? 'bg-[#06B6D4] text-black border-cyan-400 shadow-md shadow-cyan-500/20'
                            : 'bg-[#161626]/80 text-[#CBC7E0] border-white/5 hover:border-white/20'
                        }`}
                      >
                        {net}
                      </button>
                    );
                  })}
                </div>
              </div>

              <div className="space-y-2">
                <div className="flex justify-between items-center">
                  <label className="text-[11px] font-semibold text-[#8B84A8] uppercase tracking-wider">
                    2. Má»‡nh GiÃ¡ Tháº» CÃ o
                  </label>
                  <span className="text-[10.5px] text-amber-400 font-semibold">* Chá»n Ä‘Ãºng má»‡nh giÃ¡, gá»­i sai má»‡nh giÃ¡ sáº½ bá»‹ trá»« phÃ­ pháº¡t</span>
                </div>
                <div className="grid grid-cols-3 sm:grid-cols-3 gap-2">
                  {CARD_DENOMINATIONS.map((amt) => {
                    const active = cardAmount === amt;
                    return (
                      <button
                        key={amt}
                        type="button"
                        onClick={() => setCardAmount(amt)}
                        className={`py-2.5 px-2 rounded-2xl text-center font-bold text-xs transition-all cursor-pointer border ${
                          active
                            ? 'bg-[#7C3AED] text-white border-[#9D5CF6] shadow-md shadow-[#7C3AED]/30'
                            : 'bg-[#161626]/80 text-[#CBC7E0] border-white/5 hover:border-white/20'
                        }`}
                      >
                        {amt.toLocaleString('vi-VN')}Ä‘
                      </button>
                    );
                  })}
                </div>
              </div>

              <div className="grid grid-cols-1 sm:grid-cols-2 gap-4 pt-2">
                <div className="space-y-1.5">
                  <label className="text-[11px] font-semibold text-[#8B84A8] uppercase tracking-wider">Sá»‘ Serial Tháº»</label>
                  <input
                    type="text"
                    required
                    placeholder="Nháº­p dÃ£y sá»‘ Serial..."
                    value={cardSerial}
                    onChange={(e) => setCardSerial(e.target.value.replace(/[^a-zA-Z0-9]/g, ''))}
                    className="w-full bg-[#161626]/90 border border-white/10 rounded-2xl px-4 py-3 text-xs text-[#F0EDFF] font-mono tracking-wider focus:outline-none focus:border-cyan-400"
                  />
                </div>

                <div className="space-y-1.5">
                  <label className="text-[11px] font-semibold text-[#8B84A8] uppercase tracking-wider">MÃ£ Tháº» CÃ o (MÃ£ PIN)</label>
                  <input
                    type="text"
                    required
                    placeholder="Nháº­p mÃ£ náº¡p tháº» dÆ°á»›i lá»›p cÃ o..."
                    value={cardPin}
                    onChange={(e) => setCardPin(e.target.value.replace(/[^a-zA-Z0-9]/g, ''))}
                    className="w-full bg-[#161626]/90 border border-white/10 rounded-2xl px-4 py-3 text-xs text-[#F0EDFF] font-mono tracking-wider focus:outline-none focus:border-amber-400"
                  />
                </div>
              </div>

              <Button
                type="submit"
                variant="primary"
                size="lg"
                className="w-full justify-center text-sm font-bold shadow-lg shadow-[#7C3AED]/20 cursor-pointer disabled:opacity-50"
                disabled={isSubmittingCard || !cardSerial || !cardPin}
                isLoading={isSubmittingCard}
                leftIcon={<CreditCard className="w-4 h-4" />}
              >
                Gá»­i Tháº» CÃ o Ngay
              </Button>
            </div>

            {/* Right: Real-time Calculation & Notice */}
            <div className="lg:col-span-5 space-y-6">
              <div className="bg-[rgba(255,255,255,0.05)] backdrop-blur-[26px] border border-white/10 shadow-[0_20px_60px_rgba(0,0,0,0.35)] rounded-3xl p-6 space-y-4">
                <h4 className="font-bold text-xs text-[#F0EDFF] uppercase tracking-wider flex items-center gap-2">
                  <Info className="w-4 h-4 text-cyan-400" />
                  Báº£ng TÃ­nh Chiáº¿t Kháº¥u Gáº¡ch Tháº»
                </h4>

                <div className="space-y-2 text-xs">
                  <div className="p-3 rounded-2xl bg-[#161626]/80 border border-white/5 flex justify-between">
                    <span className="text-[#8B84A8]">Loáº¡i tháº»:</span>
                    <span className="font-bold text-[#F0EDFF]">{cardNetwork}</span>
                  </div>

                  <div className="p-3 rounded-2xl bg-[#161626]/80 border border-white/5 flex justify-between">
                    <span className="text-[#8B84A8]">Má»‡nh giÃ¡ gá»­i:</span>
                    <span className="font-bold text-[#F0EDFF]">{cardAmount.toLocaleString('vi-VN')}Ä‘</span>
                  </div>

                  <div className="p-3 rounded-2xl bg-[#161626]/80 border border-white/5 flex justify-between">
                    <span className="text-[#8B84A8]">Chiáº¿t kháº¥u há»‡ thá»‘ng:</span>
                    <span className="font-bold text-amber-400">-{cardFeePercent}%</span>
                  </div>

                  <div className="p-4 rounded-2xl bg-[#7C3AED]/15 border border-[#7C3AED]/40 flex justify-between items-baseline">
                    <span className="text-xs text-[#CBC7E0] font-semibold">Thá»±c nháº­n vÃ o vÃ­:</span>
                    <span className="font-display font-extrabold text-lg text-emerald-400">
                      +{cardReceiveAmount.toLocaleString('vi-VN')} <span className="text-xs">Ä‘</span>
                    </span>
                  </div>
                </div>

                <div className="p-3.5 rounded-2xl bg-amber-500/10 border border-amber-500/20 text-[11px] text-amber-200/90 leading-relaxed space-y-1">
                  <div className="font-bold">LÆ°u Ã½ quan trá»ng:</div>
                  <div>â€¢ Há»‡ thá»‘ng duyá»‡t tháº» cÃ o tá»± Ä‘á»™ng 24/7 tá»« 30s - 3 phÃºt.</div>
                  <div>â€¢ Vui lÃ²ng chá»n chÃ­nh xÃ¡c má»‡nh giÃ¡ tháº» Ä‘á»ƒ trÃ¡nh máº¥t tháº» hoáº·c bá»‹ trá»« phÃ­ sai má»‡nh giÃ¡.</div>
                </div>
              </div>
            </div>
          </form>

          {/* User's Card Recharge History */}
          <div className="bg-[rgba(255,255,255,0.05)] backdrop-blur-[26px] border border-white/10 shadow-[0_20px_60px_rgba(0,0,0,0.35)] rounded-3xl p-6 sm:p-8 space-y-4">
            <div className="flex items-center justify-between">
              <div className="flex items-center gap-2">
                <Clock className="w-4 h-4 text-cyan-400" />
                <h3 className="font-display font-bold text-sm sm:text-base text-[#F0EDFF]">
                  Lá»‹ch sá»­ náº¡p tháº» cÃ o cá»§a báº¡n
                </h3>
              </div>
              <span className="text-xs text-[#8B84A8]">{userCards.length} tháº» Ä‘Ã£ gá»­i</span>
            </div>

            {userCards.length === 0 ? (
              <div className="p-8 text-center text-xs text-[#8B84A8] border border-dashed border-white/5 rounded-2xl bg-[#161626]/30">
                Báº¡n chÆ°a gá»­i tháº» cÃ o nÃ o. HÃ£y Ä‘iá»n thÃ´ng tin bÃªn trÃªn Ä‘á»ƒ náº¡p tháº»!
              </div>
            ) : (
              <div className="overflow-x-auto">
                <table className="w-full text-left text-xs">
                  <thead>
                    <tr className="border-b border-white/5 text-[#8B84A8] text-[11px] uppercase">
                      <th className="pb-3 font-semibold">MÃ£ GD</th>
                      <th className="pb-3 font-semibold">NhÃ  Máº¡ng</th>
                      <th className="pb-3 font-semibold">Má»‡nh GiÃ¡</th>
                      <th className="pb-3 font-semibold">Thá»±c Nháº­n</th>
                      <th className="pb-3 font-semibold">Thá»i Gian</th>
                      <th className="pb-3 font-semibold text-right">Tráº¡ng ThÃ¡i</th>
                    </tr>
                  </thead>
                  <tbody className="divide-y divide-white/5">
                    {userCards.map((c) => (
                      <tr key={c.id} className="hover:bg-white/[0.02] transition-colors">
                        <td className="py-3 font-mono font-bold text-cyan-400">{c.code}</td>
                        <td className="py-3 font-semibold text-[#F0EDFF]">{c.network}</td>
                        <td className="py-3 font-bold text-[#CBC7E0]">{c.declaredAmount.toLocaleString('vi-VN')}Ä‘</td>
                        <td className="py-3 font-display font-bold text-emerald-400">
                          +{c.receivedAmount.toLocaleString('vi-VN')}Ä‘
                        </td>
                        <td className="py-3 text-[#8B84A8] font-mono text-[11px]">{c.createdAt}</td>
                        <td className="py-3 text-right">
                          {c.status === 'pending' && (
                            <Badge variant="warning" size="xs" dot>
                              Äang Xá»­ LÃ½
                            </Badge>
                          )}
                          {c.status === 'success' && (
                            <Badge variant="success" size="xs">
                              ThÃ nh CÃ´ng
                            </Badge>
                          )}
                          {c.status === 'invalid' && (
                            <Badge variant="danger" size="xs">
                              Tháº» Sai / ÄÃ£ DÃ¹ng
                            </Badge>
                          )}
                          {c.status === 'failed' && (
                            <Badge variant="neutral" size="xs">
                              Tháº¥t Báº¡i
                            </Badge>
                          )}
                        </td>
                      </tr>
                    ))}
                  </tbody>
                </table>
              </div>
            )}
          </div>
        </div>
      )}
    </div>
  );
};

