import React, { useState, useMemo, useEffect } from 'react';
import { useStore } from '../../context/StoreContext';
import { Button } from '../ui/Button';
import { Badge } from '../ui/Badge';
import { CardNetwork } from '../../types';
import {
  QrCode,
  Copy,
  Check,
  CheckCircle2,
  Clock,
  AlertCircle,
  Sparkles,
  Zap,
  Wallet,
  Building2,
  CreditCard,
  UserCheck,
  Send,
  PhoneCall,
  MessageSquare,
  Lock,
  ArrowRight,
  ShieldCheck,
  Smartphone,
  Info,
} from 'lucide-react';

const PRESET_AMOUNTS = [
  10000,
  50000,
  100000,
  200000,
  500000,
  1000000,
  2000000,
  5000000,
  10000000,
];

const CARD_DENOMINATIONS = [
  10000,
  20000,
  30000,
  50000,
  100000,
  200000,
  300000,
  500000,
  1000000,
];

export const StorefrontDepositQR: React.FC = () => {
  const {
    settings,
    currentUser,
    isAuthenticated,
    topups,
    cardRecharges,
    createTopupRequest,
    createCardRecharge,
    showToast,
    navigateToStorefront,
  } = useStore();

  // Channel switcher: VietQR Bank vs Card Recharge
  const [depositChannel, setDepositChannel] = useState<'vietqr' | 'card'>('vietqr');

  // Card Recharge State
  const [cardNetwork, setCardNetwork] = useState<CardNetwork>('Viettel');
  const [cardAmount, setCardAmount] = useState<number>(50000);
  const [cardSerial, setCardSerial] = useState<string>('');
  const [cardPin, setCardPin] = useState<string>('');
  const [isSubmittingCard, setIsSubmittingCard] = useState<boolean>(false);

  const minDeposit = settings.minDeposit || 10000;
  const maxDeposit = settings.maxDeposit || 10000000;

  // Selected or typed amount. Initial state is 0 (NO QR generated by default)
  const [selectedPreset, setSelectedPreset] = useState<number | null>(null);
  const [customAmountText, setCustomAmountText] = useState<string>('');
  const [activeAmount, setActiveAmount] = useState<number>(0);
  const [isTyping, setIsTyping] = useState<boolean>(false);

  const [copiedField, setCopiedField] = useState<string | null>(null);
  const [isSubmitting, setIsSubmitting] = useState<boolean>(false);
  const [lastSubmittedCode, setLastSubmittedCode] = useState<string | null>(null);
  const [qrLoadError, setQrLoadError] = useState<boolean>(false);

  // Dynamic Transaction Code for current valid amount session (STT<random_code>)
  const [transactionCode, setTransactionCode] = useState<string>('');

  // Generate a fresh unique transaction code when a valid amount is selected (STT + alphanumeric)
  const generateNewTransactionCode = () => {
    const prefix = (settings.transferPrefix || 'STT').trim();
    const chars = '23456789ABCDEFGHJKLMNPQRSTUVWXYZ';
    let randomPart = '';
    for (let i = 0; i < 6; i++) {
      randomPart += chars.charAt(Math.floor(Math.random() * chars.length));
    }
    return `${prefix}${randomPart}`;
  };

  // Handle Preset Click
  const handleSelectPreset = (amt: number) => {
    setIsTyping(false);
    setSelectedPreset(amt);
    setCustomAmountText(amt.toLocaleString('vi-VN'));
    setActiveAmount(amt);
    setQrLoadError(false);
    // Always generate a new unique code on amount selection
    setTransactionCode(generateNewTransactionCode());
  };

  // Debounced Custom Amount Input
  useEffect(() => {
    if (!isTyping) return;

    const timer = setTimeout(() => {
      const numericValue = parseInt(customAmountText.replace(/\D/g, ''), 10);
      if (!customAmountText || isNaN(numericValue) || numericValue === 0) {
        setActiveAmount(0);
        setSelectedPreset(null);
        setTransactionCode('');
      } else {
        setActiveAmount(numericValue);
        setSelectedPreset(PRESET_AMOUNTS.includes(numericValue) ? numericValue : null);
        if (numericValue >= minDeposit && numericValue <= maxDeposit) {
          setTransactionCode(generateNewTransactionCode());
        } else {
          setTransactionCode('');
        }
      }
    }, 250);

    return () => clearTimeout(timer);
  }, [customAmountText, isTyping, minDeposit, maxDeposit]);

  const handleCustomAmountChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    setIsTyping(true);
    const raw = e.target.value.replace(/\D/g, '');
    if (!raw) {
      setCustomAmountText('');
      setActiveAmount(0);
      setSelectedPreset(null);
      setTransactionCode('');
      return;
    }
    const num = parseInt(raw, 10);
    if (isNaN(num)) {
      setCustomAmountText('');
      setActiveAmount(0);
      setSelectedPreset(null);
      setTransactionCode('');
    } else {
      setCustomAmountText(num.toLocaleString('vi-VN'));
    }
  };

  // Validation logic
  const isAmountEntered = activeAmount > 0;
  const isBelowMin = isAmountEntered && activeAmount < minDeposit;
  const isAboveMax = isAmountEntered && activeAmount > maxDeposit;
  const isValidAmount = isAmountEntered && !isBelowMin && !isAboveMax;

  // Safe extraction helpers to prevent object as child errors
  const safeAccountNumber = typeof settings.bankAccount === 'string' ? settings.bankAccount : (settings.bankAccount as any)?.accountNumber || '0326884292';
  const safeBankName = typeof settings.bankName === 'string' ? settings.bankName : (settings.bankAccount as any)?.bankName || 'MBBank Quân Đội';
  const safeBankCode = typeof settings.bankCode === 'string' ? settings.bankCode : 'MB';
  const safeAccountHolder = typeof settings.accountHolder === 'string' ? settings.accountHolder : (settings.bankAccount as any)?.accountHolder || 'TRAN QUANG THANH';

  // Generate VietQR URL ONLY when amount is valid and bank config is available
  const qrUrl = useMemo(() => {
    if (!isValidAmount || !transactionCode) return null;

    const bankCode = safeBankCode;
    const bankAccount = safeAccountNumber;
    const accountHolder = encodeURIComponent(safeAccountHolder);
    const memo = encodeURIComponent(transactionCode);
    const template = settings.qrTemplate || 'compact2';

    return `https://img.vietqr.io/image/${bankCode}-${bankAccount}-${template}.png?amount=${activeAmount}&addInfo=${memo}&accountName=${accountHolder}`;
  }, [isValidAmount, activeAmount, transactionCode, safeBankCode, safeAccountNumber, safeAccountHolder, settings.qrTemplate]);

  const copyToClipboard = (text: string, fieldName: string) => {
    navigator.clipboard.writeText(text);
    setCopiedField(fieldName);
    showToast(`Đã sao chép ${fieldName}`, 'success');
    setTimeout(() => setCopiedField(null), 2000);
  };

  const handleSubmitDeposit = () => {
    if (!isAuthenticated) {
      showToast('Vui lòng đăng nhập tài khoản trước khi tạo yêu cầu nạp tiền.', 'warning');
      return;
    }
    if (!isValidAmount) {
      if (activeAmount < minDeposit) {
        showToast(`Số tiền nạp tối thiểu là ${minDeposit.toLocaleString('vi-VN')}đ`, 'error');
      } else if (activeAmount > maxDeposit) {
        showToast(`Số tiền nạp tối đa là ${maxDeposit.toLocaleString('vi-VN')}đ`, 'error');
      } else {
        showToast('Vui lòng chọn hoặc nhập số tiền nạp hợp lệ', 'error');
      }
      return;
    }
    if (!transactionCode) {
      showToast('Mã giao dịch không hợp lệ, vui lòng chọn lại số tiền', 'error');
      return;
    }
    setIsSubmitting(true);
    setTimeout(() => {
      const code = createTopupRequest(activeAmount, paymentMethod, transactionCode);
      setIsSubmitting(false);
      showToast(`Đã tạo yêu cầu nạp tiền ${activeAmount.toLocaleString('vi-VN')}đ thành công!`, 'success');
    }, 400);
  };

  const handleCardRechargeSubmit = (e: React.FormEvent) => {
    e.preventDefault();
    if (!isAuthenticated) {
      showToast('Vui lòng đăng nhập tài khoản trước khi nạp thẻ cào.', 'warning');
      return;
    }
    if (!cardSerial.trim() || cardSerial.trim().length < 6) {
      showToast('Vui lòng nhập số Serial thẻ hợp lệ (tối thiểu 6 ký tự)', 'error');
      return;
    }
    if (!cardPin.trim() || cardPin.trim().length < 6) {
      showToast('Vui lòng nhập Mã Thẻ (PIN) hợp lệ (tối thiểu 6 ký tự)', 'error');
      return;
    }
    setIsSubmittingCard(true);
    setTimeout(() => {
      createCardRecharge(cardNetwork, cardAmount, cardSerial.trim(), cardPin.trim());
      setCardSerial('');
      setCardPin('');
      setIsSubmittingCard(false);
    }, 500);
  };

  const userTopups = useMemo(() => {
    return topups.filter((t) => t.userId === currentUser.id);
  }, [topups, currentUser.id]);

  const userCards = useMemo(() => {
    return cardRecharges.filter((c) => c.userId === currentUser.id);
  }, [cardRecharges, currentUser.id]);

  const cardFeePercent = settings.cardSettings?.feePercentage ?? 15;
  const cardReceiveAmount = Math.round(cardAmount * (1 - cardFeePercent / 100));

  return (
    <div className="max-w-5xl mx-auto space-y-8 py-4">
      {!isAuthenticated && (
        <div className="p-4 rounded-2xl bg-amber-500/10 border border-amber-500/30 flex flex-col sm:flex-row sm:items-center justify-between gap-4">
          <div className="flex items-center gap-3">
            <Lock className="w-5 h-5 text-amber-400 flex-shrink-0" />
            <div>
              <div className="font-bold text-xs text-amber-200">Bạn chưa đăng nhập tài khoản</div>
              <div className="text-[11px] text-amber-300/80">
                Hãy đăng nhập để hệ thống tự động cộng tiền vào ví tài khoản của bạn sau khi chuyển khoản hoặc gửi thẻ cào.
              </div>
            </div>
          </div>
          <button
            onClick={() => navigateToStorefront('account')}
            className="px-4 py-2 rounded-xl bg-amber-500 hover:bg-amber-600 text-black text-xs font-bold transition-colors cursor-pointer self-start sm:self-auto flex items-center gap-1.5 whitespace-nowrap"
          >
            Đăng Nhập Ngay <ArrowRight className="w-3.5 h-3.5" />
          </button>
        </div>
      )}

      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4 border-b border-white/5 pb-6">
        <div>
          <div className="flex items-center gap-2 text-xs text-[#8B84A8] mb-1.5">
            <button onClick={() => navigateToStorefront('home')} className="hover:text-white transition-colors cursor-pointer">Trang Chủ</button>
            <span>/</span>
            <button onClick={() => navigateToStorefront('account')} className="hover:text-white transition-colors cursor-pointer">Tài Khoản</button>
            <span>/</span>
            <span className="text-[#9D5CF6] font-medium">Nạp tiền</span>
          </div>
          <h1 className="font-display text-2xl sm:text-3xl font-extrabold text-[#F0EDFF] tracking-tight">
            Nạp tiền vào tài khoản
          </h1>
          <p className="text-xs sm:text-sm text-[#8B84A8] mt-1 font-medium">
            Hỗ trợ chuyển khoản ngân hàng VietQR tự động 24/7 và gạch thẻ cào điện thoại / game
          </p>
        </div>

        <div className="flex items-center gap-3 bg-[rgba(255,255,255,0.05)] backdrop-blur-[26px] border border-white/10 p-3.5 rounded-2xl shadow-[0_10px_30px_rgba(0,0,0,0.25)]">
          <div className="w-10 h-10 rounded-xl bg-[#7C3AED]/20 border border-[#7C3AED]/30 flex items-center justify-center text-[#9D5CF6]">
            <Wallet className="w-5 h-5" />
          </div>
          <div>
            <div className="text-[11px] font-semibold text-[#8B84A8] uppercase tracking-wider">Số dư ví của bạn</div>
            <div className="font-display text-lg font-bold text-emerald-400">
              {currentUser.balance.toLocaleString('vi-VN')} <span className="text-xs font-normal">đ</span>
            </div>
          </div>
        </div>
      </div>

      <div className="flex items-center gap-3 border-b border-white/10 pb-4">
        <button
          type="button"
          onClick={() => setDepositChannel('vietqr')}
          className={`flex items-center gap-2.5 px-5 py-3 rounded-2xl font-bold text-xs transition-all cursor-pointer border ${
            depositChannel === 'vietqr'
              ? 'bg-[#7C3AED] text-white border-[#9D5CF6] shadow-lg shadow-[#7C3AED]/30'
              : 'bg-[#161626]/80 text-[#8B84A8] border-white/5 hover:text-white hover:border-white/15'
          }`}
        >
          <QrCode className="w-4 h-4" />
          <span>Chuyển Khoản Ngân Hàng (VietQR)</span>
          <span className="px-1.5 py-0.5 rounded-md text-[10px] bg-emerald-400/20 text-emerald-300 font-bold ml-1">
            Khuyên Dùng
          </span>
        </button>

        <button
          type="button"
          onClick={() => setDepositChannel('card')}
          className={`flex items-center gap-2.5 px-5 py-3 rounded-2xl font-bold text-xs transition-all cursor-pointer border ${
            depositChannel === 'card'
              ? 'bg-[#7C3AED] text-white border-[#9D5CF6] shadow-lg shadow-[#7C3AED]/30'
              : 'bg-[#161626]/80 text-[#8B84A8] border-white/5 hover:text-white hover:border-white/15'
          }`}
        >
          <Smartphone className="w-4 h-4" />
          <span>Nạp Thẻ Cào Điện Thoại / Game</span>
          <span className="px-1.5 py-0.5 rounded-md text-[10px] bg-amber-400/20 text-amber-300 font-bold ml-1">
            Chiết khấu {cardFeePercent}%
          </span>
        </button>
      </div>

      {depositChannel === 'vietqr' && (
        <>
          <div className="grid grid-cols-1 lg:grid-cols-12 gap-6">
            <div className="lg:col-span-5 space-y-6">
              <div className="bg-[rgba(255,255,255,0.05)] backdrop-blur-[26px] border border-white/10 shadow-[0_20px_60px_rgba(0,0,0,0.35)] rounded-3xl p-6 space-y-3">
                <div className="flex items-center gap-2 text-xs font-bold text-[#F0EDFF] uppercase tracking-wider">
                  <Building2 className="w-4 h-4 text-[#9D5CF6]" />
                  <span>Kênh Chuyển Khoản MBBank</span>
                </div>
                <div className="p-3.5 rounded-2xl bg-[#161626]/80 border border-white/5 space-y-1">
                  <div className="text-xs font-semibold text-[#F0EDFF]">
                    {safeBankName} ({safeBankCode})
                  </div>
                  <div className="text-[11px] text-[#8B84A8]">
                    STK: <strong className="font-mono text-cyan-400">{safeAccountNumber}</strong>
                  </div>
                  <div className="text-[11px] text-[#8B84A8]">
                    Chủ TK: <strong className="text-white">{safeAccountHolder}</strong>
                  </div>
                </div>
              </div>

              <div className="bg-[rgba(255,255,255,0.05)] backdrop-blur-[26px] border border-white/10 shadow-[0_20px_60px_rgba(0,0,0,0.35)] rounded-3xl p-6 space-y-4">
                <div className="flex items-center justify-between">
                  <div className="flex items-center gap-2 text-xs font-bold text-[#F0EDFF] uppercase tracking-wider">
                    <Sparkles className="w-4 h-4 text-amber-400" />
                    <span>Chọn số tiền nạp</span>
                  </div>
                  <span className="text-[11px] font-semibold text-[#9D5CF6]">
                    {minDeposit.toLocaleString('vi-VN')}đ – {maxDeposit.toLocaleString('vi-VN')}đ
                  </span>
                </div>

                <div className="space-y-1.5">
                  <label className="text-[11px] font-semibold text-[#8B84A8]">Nhập số tiền:</label>
                  <div className="relative">
                    <input
                      type="text"
                      placeholder="Nhập số tiền (VD: 50,000 / 200,000)..."
                      value={customAmountText}
                      onChange={handleCustomAmountChange}
                      className={`w-full bg-[#161626]/90 border rounded-2xl pl-4 pr-10 py-3 text-sm text-[#F0EDFF] font-bold focus:outline-none transition-colors ${
                        isBelowMin || isAboveMax
                          ? 'border-red-500/60 focus:border-red-500'
                          : isValidAmount
                          ? 'border-emerald-500/60 focus:border-emerald-500'
                          : 'border-white/10 focus:border-[#7C3AED]'
                      }`}
                    />
                    <span className="absolute right-3.5 top-1/2 -translate-y-1/2 text-xs font-bold text-[#8B84A8]">
                      VNĐ
                    </span>
                  </div>

                  {isBelowMin && (
                    <p className="text-[11px] text-red-400 flex items-center gap-1 font-medium pt-0.5">
                      <AlertCircle className="w-3.5 h-3.5" />
                      Số tiền nạp tối thiểu là {minDeposit.toLocaleString('vi-VN')}đ
                    </p>
                  )}
                  {isAboveMax && (
                    <p className="text-[11px] text-red-400 flex items-center gap-1 font-medium pt-0.5">
                      <AlertCircle className="w-3.5 h-3.5" />
                      Số tiền nạp tối đa là {maxDeposit.toLocaleString('vi-VN')}đ
                    </p>
                  )}
                </div>

                <div className="space-y-1.5 pt-1">
                  <div className="text-[11px] font-semibold text-[#8B84A8]">Mức nạp phổ biến:</div>
                  <div className="grid grid-cols-3 gap-2">
                    {PRESET_AMOUNTS.map((amt) => {
                      const active = selectedPreset === amt;
                      const label =
                        amt >= 1000000
                          ? `${amt / 1000000}M`
                          : amt >= 1000
                          ? `${amt / 1000}K`
                          : `${amt}`;
                      return (
                        <button
                          key={amt}
                          type="button"
                          onClick={() => handleSelectPreset(amt)}
                          className={`py-2.5 px-2 rounded-2xl text-center font-bold text-xs transition-all cursor-pointer border ${
                            active
                              ? 'bg-[#7C3AED] text-white border-[#9D5CF6] shadow-md shadow-[#7C3AED]/30 scale-[1.02]'
                              : 'bg-[#161626]/80 text-[#CBC7E0] border-white/5 hover:border-white/20 hover:text-white'
                          }`}
                        >
                          {label}
                          <span className="text-[10px] font-normal text-white/70 block">
                            {amt.toLocaleString('vi-VN')}đ
                          </span>
                        </button>
                      );
                    })}
                  </div>
                </div>

                {isValidAmount && (
                  <div className="p-3.5 rounded-2xl bg-[#7C3AED]/15 border border-[#7C3AED]/30 flex items-center justify-between text-xs">
                    <span className="text-[#CBC7E0] font-medium">Số tiền thanh toán:</span>
                    <span className="font-display font-extrabold text-lg text-emerald-400">
                      {activeAmount.toLocaleString('vi-VN')} <span className="text-xs font-bold text-emerald-300">đ</span>
                    </span>
                  </div>
                )}
              </div>

              <div className="p-5 rounded-3xl bg-[rgba(255,255,255,0.05)] backdrop-blur-[26px] border border-white/10 text-xs space-y-2.5">
                <div className="flex items-center gap-2 font-bold text-[#F0EDFF]">
                  <MessageSquare className="w-4 h-4 text-[#9D5CF6]" />
                  <span>Hỗ trợ nạp tiền 24/7</span>
                </div>
                <p className="text-[11.5px] leading-relaxed text-[#8B84A8]">
                  Nếu giao dịch chưa cộng tiền sau 3-5 phút, vui lòng liên hệ Admin để được hỗ trợ kiểm tra tức thì:
                </p>
                <div className="grid grid-cols-2 gap-2 pt-1">
                  <a
                    href="https://t.me/quangthank"
                    target="_blank"
                    rel="noreferrer"
                    className="p-2.5 rounded-xl bg-[#161626]/80 border border-white/5 hover:border-[#06B6D4]/40 flex items-center gap-1.5 text-[11px] text-[#06B6D4] font-semibold transition-colors"
                  >
                    <Send className="w-3.5 h-3.5" />
                    <span className="truncate">Telegram: @quangthank</span>
                  </a>
                  <a
                    href="https://zalo.me/0916396901"
                    target="_blank"
                    rel="noreferrer"
                    className="p-2.5 rounded-xl bg-[#161626]/80 border border-white/5 hover:border-emerald-400/40 flex items-center gap-1.5 text-[11px] text-emerald-400 font-semibold transition-colors"
                  >
                    <PhoneCall className="w-3.5 h-3.5" />
                    <span className="truncate">Zalo: 0916396901</span>
                  </a>
                </div>
              </div>
            </div>

            <div className="lg:col-span-7 space-y-6">
              <div className="bg-[rgba(255,255,255,0.05)] backdrop-blur-[26px] border border-white/10 shadow-[0_20px_60px_rgba(0,0,0,0.35)] rounded-3xl p-6 sm:p-8 space-y-6">
                <div className="flex items-center justify-between border-b border-white/5 pb-4">
                  <div>
                    <h3 className="font-display font-bold text-base sm:text-lg text-[#F0EDFF] flex items-center gap-2">
                      <QrCode className="w-5 h-5 text-[#9D5CF6]" />
                      Mã QR thanh toán
                    </h3>
                    <p className="text-xs text-[#8B84A8] mt-0.5">
                      {isValidAmount
                        ? 'Quét mã để tự động điền số tiền và nội dung chuyển khoản chính xác'
                        : 'Vui lòng chọn hoặc nhập số tiền để tạo mã QR thanh toán'}
                    </p>
                  </div>
                  <Badge variant="brand" size="sm" dot>
                    VietQR 24/7
                  </Badge>
                </div>

                {!isValidAmount ? (
                  <div className="py-14 px-6 rounded-2xl border border-dashed border-white/10 bg-[#161626]/40 text-center space-y-3">
                    <div className="w-16 h-16 rounded-2xl bg-white/5 border border-white/10 mx-auto flex items-center justify-center text-[#8B84A8]">
                      <QrCode className="w-8 h-8 opacity-60" />
                    </div>
                    <div>
                      <h4 className="font-display font-bold text-sm text-[#F0EDFF] uppercase tracking-wider">
                        Chưa có mã QR
                      </h4>
                      <p className="text-xs text-[#8B84A8] mt-1 max-w-sm mx-auto">
                        Vui lòng chọn hoặc nhập số tiền từ{' '}
                        <strong className="text-white">{minDeposit.toLocaleString('vi-VN')}đ</strong> đến{' '}
                        <strong className="text-white">{maxDeposit.toLocaleString('vi-VN')}đ</strong> để tạo mã QR thanh toán.
                      </p>
                    </div>
                  </div>
                ) : (
                  <div className="grid grid-cols-1 sm:grid-cols-12 gap-6 items-center">
                    <div className="sm:col-span-6 flex flex-col items-center">
                      <div className="p-3 sm:p-4 bg-white rounded-2xl shadow-2xl shadow-black/60 border border-white/20 w-full max-w-[280px] sm:max-w-[300px] flex items-center justify-center">
                        {qrLoadError ? (
                          <div className="aspect-square w-full flex flex-col items-center justify-center p-4 text-center text-zinc-800">
                            <AlertCircle className="w-8 h-8 text-red-500 mb-2" />
                            <p className="text-xs font-bold">Không thể tải mã QR</p>
                            <button
                              type="button"
                              onClick={() => setQrLoadError(false)}
                              className="mt-3 px-3 py-1 bg-zinc-900 text-white text-[10px] font-bold rounded-lg cursor-pointer"
                            >
                              Thử lại
                            </button>
                          </div>
                        ) : (
                          <img
                            src={qrUrl!}
                            alt={`VietQR ${activeAmount} VND`}
                            onError={() => setQrLoadError(true)}
                            className="w-full aspect-square object-contain rounded-lg"
                            referrerPolicy="no-referrer"
                          />
                        )}
                      </div>
                      <div className="mt-3 text-[11px] text-[#CBC7E0] text-center flex items-center gap-1.5 font-medium">
                        <Zap className="w-3.5 h-3.5 text-amber-400" />
                        Mở App Ngân Hàng → Quét mã chuyển khoản
                      </div>
                    </div>

                    <div className="sm:col-span-6 space-y-2.5 text-xs">
                      <div className="p-3 rounded-2xl bg-[#161626]/80 border border-white/5 flex items-center justify-between">
                        <div>
                          <div className="text-[10px] uppercase font-bold text-[#8B84A8]">Ngân hàng nhận</div>
                          <div className="font-bold text-[#F0EDFF] text-xs mt-0.5">
                            {safeBankName} ({safeBankCode})
                          </div>
                        </div>
                        <Building2 className="w-4 h-4 text-[#8B84A8]" />
                      </div>

                      <div className="p-3 rounded-2xl bg-[#161626]/80 border border-white/5 flex items-center justify-between">
                        <div>
                          <div className="text-[10px] uppercase font-bold text-[#8B84A8]">Số tài khoản</div>
                          <div className="font-mono font-bold text-sm text-[#06B6D4] mt-0.5">
                            {safeAccountNumber}
                          </div>
                        </div>
                        <button
                          type="button"
                          onClick={() => copyToClipboard(safeAccountNumber, 'Số tài khoản')}
                          className="p-2 rounded-xl bg-white/5 hover:bg-white/10 text-[#CBC7E0] transition-colors cursor-pointer"
                        >
                          {copiedField === 'Số tài khoản' ? (
                            <Check className="w-3.5 h-3.5 text-emerald-400" />
                          ) : (
                            <Copy className="w-3.5 h-3.5" />
                          )}
                        </button>
                      </div>

                      <div className="p-3 rounded-2xl bg-[#161626]/80 border border-white/5 flex items-center justify-between">
                        <div>
                          <div className="text-[10px] uppercase font-bold text-[#8B84A8]">Chủ tài khoản</div>
                          <div className="font-bold text-[#F0EDFF] uppercase text-xs mt-0.5">
                            {safeAccountHolder}
                          </div>
                        </div>
                        <UserCheck className="w-4 h-4 text-[#8B84A8]" />
                      </div>

                      <div className="p-3 rounded-2xl bg-[#161626]/80 border border-white/5 flex items-center justify-between">
                        <div>
                          <div className="text-[10px] uppercase font-bold text-[#8B84A8]">Số tiền</div>
                          <div className="font-display font-bold text-sm text-emerald-400 mt-0.5">
                            {activeAmount.toLocaleString('vi-VN')} VND
                          </div>
                        </div>
                        <button
                          type="button"
                          onClick={() => copyToClipboard(activeAmount.toString(), 'Số tiền')}
                          className="p-2 rounded-xl bg-white/5 hover:bg-white/10 text-[#CBC7E0] transition-colors cursor-pointer"
                        >
                          {copiedField === 'Số tiền' ? (
                            <Check className="w-3.5 h-3.5 text-emerald-400" />
                          ) : (
                            <Copy className="w-3.5 h-3.5" />
                          )}
                        </button>
                      </div>

                      <div className="p-3 rounded-2xl bg-[#7C3AED]/15 border border-[#7C3AED]/40 flex items-center justify-between">
                        <div>
                          <div className="text-[10px] uppercase font-bold text-[#9D5CF6]">
                            Nội dung chuyển khoản (Bắt buộc)
                          </div>
                          <div className="font-mono font-bold text-xs text-amber-300 tracking-wider mt-0.5">
                            {transactionCode}
                          </div>
                        </div>
                        <button
                          type="button"
                          onClick={() => copyToClipboard(transactionCode, 'Nội dung')}
                          className="p-2 rounded-xl bg-[#7C3AED]/30 hover:bg-[#7C3AED]/50 text-[#F0EDFF] transition-colors cursor-pointer"
                        >
                          {copiedField === 'Nội dung' ? (
                            <Check className="w-3.5 h-3.5 text-emerald-400" />
                          ) : (
                            <Copy className="w-3.5 h-3.5" />
                          )}
                        </button>
                      </div>
                    </div>
                  </div>
                )}

                <div className="pt-4 border-t border-white/5 space-y-3">
                  <Button
                    variant="primary"
                    size="lg"
                    className="w-full justify-center text-sm font-bold shadow-lg shadow-[#7C3AED]/20 cursor-pointer disabled:opacity-50 disabled:cursor-not-allowed"
                    disabled={!isValidAmount || isSubmitting || !transactionCode}
                    isLoading={isSubmitting}
                    onClick={handleSubmitDeposit}
                    leftIcon={<CheckCircle2 className="w-4 h-4" />}
                  >
                    Tôi Đã Chuyển Khoản — Xác Nhận Nạp Tiền
                  </Button>

                  <div className="flex items-center justify-center gap-1.5 text-[11px] text-[#8B84A8]">
                    <ShieldCheck className="w-3.5 h-3.5 text-[#9D5CF6]" />
                    <span>
                      Hệ thống tự động đối soát và cộng tiền trong 1-3 phút. Nếu quá 5 phút, vui lòng liên hệ hỗ trợ.
                    </span>
                  </div>
                </div>
              </div>
            </div>
          </div>

          <div className="bg-[rgba(255,255,255,0.05)] backdrop-blur-[26px] border border-white/10 shadow-[0_20px_60px_rgba(0,0,0,0.35)] rounded-3xl p-6 sm:p-8 space-y-4">
            <div className="flex items-center justify-between">
              <div className="flex items-center gap-2">
                <Clock className="w-4 h-4 text-[#9D5CF6]" />
                <h3 className="font-display font-bold text-sm sm:text-base text-[#F0EDFF]">
                  Lịch sử nạp tiền VietQR
                </h3>
              </div>
              <span className="text-xs text-[#8B84A8]">{userTopups.length} giao dịch</span>
            </div>

            {userTopups.length === 0 ? (
              <div className="p-8 text-center text-xs text-[#8B84A8] border border-dashed border-white/5 rounded-2xl bg-[#161626]/30">
                Bạn chưa có yêu cầu nạp tiền nào. Hãy chọn mức nạp bên trên để bắt đầu!
              </div>
            ) : (
              <div className="overflow-x-auto">
                <table className="w-full text-left text-xs">
                  <thead>
                    <tr className="border-b border-white/5 text-[#8B84A8] text-[11px] uppercase">
                      <th className="pb-3 font-semibold">Mã Yêu Cầu</th>
                      <th className="pb-3 font-semibold">Số Tiền</th>
                      <th className="pb-3 font-semibold">Phương Thức</th>
                      <th className="pb-3 font-semibold">Nội Dung</th>
                      <th className="pb-3 font-semibold">Thời Gian</th>
                      <th className="pb-3 font-semibold text-right">Trạng Thái</th>
                    </tr>
                  </thead>
                  <tbody className="divide-y divide-white/5">
                    {userTopups.map((topup) => (
                      <tr key={topup.id} className="hover:bg-white/[0.02] transition-colors">
                        <td className="py-3 font-mono font-bold text-[#9D5CF6]">{topup.requestCode}</td>
                        <td className="py-3 font-display font-bold text-emerald-400">
                          +{topup.amount.toLocaleString('vi-VN')}đ
                        </td>
                        <td className="py-3 text-[#CBC7E0]">{topup.method}</td>
                        <td className="py-3 font-mono text-[11px] text-[#8B84A8]">{topup.transferNote}</td>
                        <td className="py-3 text-[#8B84A8]">{topup.createdAt}</td>
                        <td className="py-3 text-right">
                          {topup.status === 'pending' && <Badge variant="warning" size="xs" dot>Chờ Duyệt</Badge>}
                          {topup.status === 'processing' && <Badge variant="warning" size="xs" dot>Đang Xử Lý</Badge>}
                          {topup.status === 'approved' && <Badge variant="success" size="xs">Đã Cộng Tiền</Badge>}
                          {topup.status === 'rejected' && <Badge variant="danger" size="xs">Từ Chối</Badge>}
                          {topup.status === 'cancelled' && <Badge variant="neutral" size="xs">Đã Hủy</Badge>}
                        </td>
                      </tr>
                    ))}
                  </tbody>
                </table>
              </div>
            )}
          </div>
        </>
      )}

      {depositChannel === 'card' && (
        <div className="space-y-6">
          <form onSubmit={handleCardRechargeSubmit} className="grid grid-cols-1 lg:grid-cols-12 gap-6">
            <div className="lg:col-span-7 bg-[rgba(255,255,255,0.05)] backdrop-blur-[26px] border border-white/10 shadow-[0_20px_60px_rgba(0,0,0,0.35)] rounded-3xl p-6 sm:p-8 space-y-5">
              <div className="flex items-center gap-2 border-b border-white/5 pb-3 font-bold text-sm text-[#F0EDFF]">
                <CreditCard className="w-4 h-4 text-[#06B6D4]" />
                <span>Nhập Thông Tin Thẻ Cào</span>
              </div>

              <div className="space-y-2">
                <label className="text-[11px] font-semibold text-[#8B84A8] uppercase tracking-wider">
                  1. Chọn Loại Thẻ / Nhà Mạng
                </label>
                <div className="grid grid-cols-3 sm:grid-cols-6 gap-2">
                  {(['Viettel', 'Vinaphone', 'Mobifone', 'Vietnamobile', 'Zing', 'Garena'] as CardNetwork[]).map((net) => {
                    const active = cardNetwork === net;
                    return (
                      <button
                        key={net}
                        type="button"
                        onClick={() => setCardNetwork(net)}
                        className={`py-2.5 px-2 rounded-2xl text-center font-bold text-xs transition-all cursor-pointer border ${
                          active
                            ? 'bg-[#06B6D4] text-black border-cyan-400 shadow-md shadow-cyan-500/20'
                            : 'bg-[#161626]/80 text-[#CBC7E0] border-white/5 hover:border-white/20'
                        }`}
                      >
                        {net}
                      </button>
                    );
                  })}
                </div>
              </div>

              <div className="space-y-2">
                <div className="flex justify-between items-center">
                  <label className="text-[11px] font-semibold text-[#8B84A8] uppercase tracking-wider">
                    2. Mệnh Giá Thẻ Cào
                  </label>
                  <span className="text-[10.5px] text-amber-400 font-semibold">* Chọn đúng mệnh giá, gửi sai mệnh giá sẽ bị trừ phí phạt</span>
                </div>
                <div className="grid grid-cols-3 sm:grid-cols-3 gap-2">
                  {CARD_DENOMINATIONS.map((amt) => {
                    const active = cardAmount === amt;
                    return (
                      <button
                        key={amt}
                        type="button"
                        onClick={() => setCardAmount(amt)}
                        className={`py-2.5 px-2 rounded-2xl text-center font-bold text-xs transition-all cursor-pointer border ${
                          active
                            ? 'bg-[#7C3AED] text-white border-[#9D5CF6] shadow-md shadow-[#7C3AED]/30'
                            : 'bg-[#161626]/80 text-[#CBC7E0] border-white/5 hover:border-white/20'
                        }`}
                      >
                        {amt.toLocaleString('vi-VN')}đ
                      </button>
                    );
                  })}
                </div>
              </div>

              <div className="grid grid-cols-1 sm:grid-cols-2 gap-4 pt-2">
                <div className="space-y-1.5">
                  <label className="text-[11px] font-semibold text-[#8B84A8] uppercase tracking-wider">Số Serial Thẻ</label>
                  <input
                    type="text"
                    required
                    placeholder="Nhập dãy số Serial..."
                    value={cardSerial}
                    onChange={(e) => setCardSerial(e.target.value.replace(/[^a-zA-Z0-9]/g, ''))}
                    className="w-full bg-[#161626]/90 border border-white/10 rounded-2xl px-4 py-3 text-xs text-[#F0EDFF] font-mono tracking-wider focus:outline-none focus:border-cyan-400"
                  />
                </div>

                <div className="space-y-1.5">
                  <label className="text-[11px] font-semibold text-[#8B84A8] uppercase tracking-wider">Mã Thẻ Cào (Mã PIN)</label>
                  <input
                    type="text"
                    required
                    placeholder="Nhập mã nạp thẻ dưới lớp cào..."
                    value={cardPin}
                    onChange={(e) => setCardPin(e.target.value.replace(/[^a-zA-Z0-9]/g, ''))}
                    className="w-full bg-[#161626]/90 border border-white/10 rounded-2xl px-4 py-3 text-xs text-[#F0EDFF] font-mono tracking-wider focus:outline-none focus:border-amber-400"
                  />
                </div>
              </div>

              <Button
                type="submit"
                variant="primary"
                size="lg"
                className="w-full justify-center text-sm font-bold shadow-lg shadow-[#7C3AED]/20 cursor-pointer disabled:opacity-50"
                disabled={isSubmittingCard || !cardSerial || !cardPin}
                isLoading={isSubmittingCard}
                leftIcon={<CreditCard className="w-4 h-4" />}
              >
                Gửi Thẻ Cào Ngay
              </Button>
            </div>

            {/* Right: Real-time Calculation & Notice */}
            <div className="lg:col-span-5 space-y-6">
              <div className="bg-[rgba(255,255,255,0.05)] backdrop-blur-[26px] border border-white/10 shadow-[0_20px_60px_rgba(0,0,0,0.35)] rounded-3xl p-6 space-y-4">
                <h4 className="font-bold text-xs text-[#F0EDFF] uppercase tracking-wider flex items-center gap-2">
                  <Info className="w-4 h-4 text-cyan-400" />
                  Bảng Tính Chiết Khấu Gạch Thẻ
                </h4>

                <div className="space-y-2 text-xs">
                  <div className="p-3 rounded-2xl bg-[#161626]/80 border border-white/5 flex justify-between">
                    <span className="text-[#8B84A8]">Loại thẻ:</span>
                    <span className="font-bold text-[#F0EDFF]">{cardNetwork}</span>
                  </div>

                  <div className="p-3 rounded-2xl bg-[#161626]/80 border border-white/5 flex justify-between">
                    <span className="text-[#8B84A8]">Mệnh giá gửi:</span>
                    <span className="font-bold text-[#F0EDFF]">{cardAmount.toLocaleString('vi-VN')}đ</span>
                  </div>

                  <div className="p-3 rounded-2xl bg-[#161626]/80 border border-white/5 flex justify-between">
                    <span className="text-[#8B84A8]">Chiết khấu hệ thống:</span>
                    <span className="font-bold text-amber-400">-{cardFeePercent}%</span>
                  </div>

                  <div className="p-4 rounded-2xl bg-[#7C3AED]/15 border border-[#7C3AED]/40 flex justify-between items-baseline">
                    <span className="text-xs text-[#CBC7E0] font-semibold">Thực nhận vào ví:</span>
                    <span className="font-display font-extrabold text-lg text-emerald-400">
                      +{cardReceiveAmount.toLocaleString('vi-VN')} <span className="text-xs">đ</span>
                    </span>
                  </div>
                </div>

                <div className="p-3.5 rounded-2xl bg-amber-500/10 border border-amber-500/20 text-[11px] text-amber-200/90 leading-relaxed space-y-1">
                  <div className="font-bold">Lưu ý quan trọng:</div>
                  <div>• Hệ thống duyệt thẻ cào tự động 24/7 từ 30s - 3 phút.</div>
                  <div>• Vui lòng chọn chính xác mệnh giá thẻ để tránh mất thẻ hoặc bị trừ phí sai mệnh giá.</div>
                </div>
              </div>
            </div>
          </form>

          {/* User's Card Recharge History */}
          <div className="bg-[rgba(255,255,255,0.05)] backdrop-blur-[26px] border border-white/10 shadow-[0_20px_60px_rgba(0,0,0,0.35)] rounded-3xl p-6 sm:p-8 space-y-4">
            <div className="flex items-center justify-between">
              <div className="flex items-center gap-2">
                <Clock className="w-4 h-4 text-cyan-400" />
                <h3 className="font-display font-bold text-sm sm:text-base text-[#F0EDFF]">
                  Lịch sử nạp thẻ cào của bạn
                </h3>
              </div>
              <span className="text-xs text-[#8B84A8]">{userCards.length} thẻ đã gửi</span>
            </div>

            {userCards.length === 0 ? (
              <div className="p-8 text-center text-xs text-[#8B84A8] border border-dashed border-white/5 rounded-2xl bg-[#161626]/30">
                Bạn chưa gửi thẻ cào nào. Hãy điền thông tin bên trên để nạp thẻ!
              </div>
            ) : (
              <div className="overflow-x-auto">
                <table className="w-full text-left text-xs">
                  <thead>
                    <tr className="border-b border-white/5 text-[#8B84A8] text-[11px] uppercase">
                      <th className="pb-3 font-semibold">Mã GD</th>
                      <th className="pb-3 font-semibold">Nhà Mạng</th>
                      <th className="pb-3 font-semibold">Mệnh Giá</th>
                      <th className="pb-3 font-semibold">Thực Nhận</th>
                      <th className="pb-3 font-semibold">Thời Gian</th>
                      <th className="pb-3 font-semibold text-right">Trạng Thái</th>
                    </tr>
                  </thead>
                  <tbody className="divide-y divide-white/5">
                    {userCards.map((c) => (
                      <tr key={c.id} className="hover:bg-white/[0.02] transition-colors">
                        <td className="py-3 font-mono font-bold text-cyan-400">{c.code}</td>
                        <td className="py-3 font-semibold text-[#F0EDFF]">{c.network}</td>
                        <td className="py-3 font-bold text-[#CBC7E0]">{c.declaredAmount.toLocaleString('vi-VN')}đ</td>
                        <td className="py-3 font-display font-bold text-emerald-400">
                          +{c.receivedAmount.toLocaleString('vi-VN')}đ
                        </td>
                        <td className="py-3 text-[#8B84A8] font-mono text-[11px]">{c.createdAt}</td>
                        <td className="py-3 text-right">
                          {c.status === 'pending' && (
                            <Badge variant="warning" size="xs" dot>
                              Đang Xử Lý
                            </Badge>
                          )}
                          {c.status === 'success' && (
                            <Badge variant="success" size="xs">
                              Thành Công
                            </Badge>
                          )}
                          {c.status === 'invalid' && (
                            <Badge variant="danger" size="xs">
                              Thẻ Sai / Đã Dùng
                            </Badge>
                          )}
                          {c.status === 'failed' && (
                            <Badge variant="neutral" size="xs">
                              Thất Bại
                            </Badge>
                          )}
                        </td>
                      </tr>
                    ))}
                  </tbody>
                </table>
              </div>
            )}
          </div>
        </div>
      )}
    </div>
  );
};
